### PR TITLE
jane's first notebook file

### PR DESCRIPTION
**Pull request by jpan1**

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @jpan1 I will check this out tonight 

-sent from a mobile device-

**Comment by scollis** [comment]
Good work @jpan1  I am not going to accept the PR just yet.. One nice thing is as you continue to commit to Master the PR will be updated. Please import Py-ART if it on your machine and if not get @jjhelmus to get it working and then read a nexrad file from:
http://www.ncdc.noaa.gov/nexradinv/displaygraphs.jsp?mm=05&dd=20&yyyy=2011&product=AAL2&filter=&id=KVNX
pick ~ 1030UTC  and make me a plot.. 
Add and commit and then push to master and this will update the PR..

Very good work..

**Comment by jpan1** [comment]
Hi Scott,

Almost there! I managed to download and read one of the files but am having
trouble seeing the plots.
Attached is a screenshot of what I have typed on iPython. Do you know why
I'm not getting any pretty pictures? Or are they hiding somewhere?

Thanks!

-Jane

On Fri, Jun 5, 2015 at 6:18 PM, Scott notifications@github.com wrote:

> Good work @jpan1 https://github.com/jpan1 I am not going to accept the
> PR just yet.. One nice thing is as you continue to commit to Master the PR
> will be updated. Please import Py-ART if it on your machine and if not get
> @jjhelmus https://github.com/jjhelmus to get it working and then read a
> nexrad file from:
> 
> http://www.ncdc.noaa.gov/nexradinv/displaygraphs.jsp?mm=05&dd=20&yyyy=2011&product=AAL2&filter=&id=KVNX
> pick ~ 1030UTC and make me a plot..
> Add and commit and then push to master and this will update the PR..
> 
> Very good work..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EVS-ATMOS/SULI-2015/pull/2#issuecomment-109479008.

## 

Jane Pan
Meyerhoff Scholar
NSA Scholar
Mathematics/Statistics
Economics Minor
University of Maryland, Baltimore County (UMBC)
Class of 2016
janepan1@umbc.edu
(c) 301-580-5634

**Comment by scollis** [comment]
Do you have
%matplotlib inline
at the top of your notebook?

On 6/8/15 10:23 AM, jpan1 wrote:

> Hi Scott,
> 
> Almost there! I managed to download and read one of the files but am 
> having
> trouble seeing the plots.
> Attached is a screenshot of what I have typed on iPython. Do you know why
> I'm not getting any pretty pictures? Or are they hiding somewhere?
> 
> Thanks!
> 
> -Jane
> 
> On Fri, Jun 5, 2015 at 6:18 PM, Scott notifications@github.com wrote:
> 
> > Good work @jpan1 https://github.com/jpan1 I am not going to accept the
> > PR just yet.. One nice thing is as you continue to commit to Master 
> > the PR
> > will be updated. Please import Py-ART if it on your machine and if 
> > not get
> > @jjhelmus https://github.com/jjhelmus to get it working and then 
> > read a
> > nexrad file from:
> > 
> > http://www.ncdc.noaa.gov/nexradinv/displaygraphs.jsp?mm=05&dd=20&yyyy=2011&product=AAL2&filter=&id=KVNX
> > pick ~ 1030UTC and make me a plot..
> > Add and commit and then push to master and this will update the PR..
> > 
> > Very good work..
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/EVS-ATMOS/SULI-2015/pull/2#issuecomment-109479008.
> 
> ## 
> 
> Jane Pan
> Meyerhoff Scholar
> NSA Scholar
> Mathematics/Statistics
> Economics Minor
> University of Maryland, Baltimore County (UMBC)
> Class of 2016
> janepan1@umbc.edu
> (c) 301-580-5634
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/EVS-ATMOS/SULI-2015/pull/2#issuecomment-110038605.

## 

I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Pull request merged**
